export const FETCHING_DATA = 'FETCHING_DATA';
export const FETCHING_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS';
export const FETCHING_DATA_FAILURE = 'FETCHING_DATA_FAILURE';

export const LOGIN_BEGIN = 'LOGIN_BEGIN'; 
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'; 
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const FETCHING_BOOKS = 'FETCHING_BOOKS';
export const FETCHING_BOOKS_SUCCESS = 'FETCHING_BOOKS_SUCCESS';
export const FETCHING_BOOKS_FAILURE = 'FETCHING_BOOKS_FAILURE';

export const playersActions = {
    FETCHING: "FETCHING_PLAYERS",
    FETCH_SUCCESS: "FETCHING_PLAYERS_SUCCESS",
    FETCH_FAILURE: "FETCHING_PLAYERS_FAILURE"
}